export { default as Home } from "./home/Home";
export { default as ContactUs } from "./contactUs/ContactUs";
export { default as Login } from "./Auth/Login";
export { default as SignUp } from "./Auth/SignUp";
export { default as Reset } from "./Auth/Reset";
export { default as Cart } from "./cart/Cart";
export { default as Admin } from "./admin/Admin";
export { default as MyOrders } from "./myOrders/MyOrders";
export { default as Payment } from "./payment/Payment";
